repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: ae7cee538b6ba3457d1307040d6d29962692e8f6
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
